spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nahida_library
    username: lkzc19
    password: 111111
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      server-addr: http://101.201.116.226:8848/
      discovery:
        username: nacos
        password: nahida
        namespace: public
