server:
  port: 9102

spring:
  profiles:
    active: local
  application:
    name: core-service

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: true # 逻辑已删除值(默认为 1)
      logic-not-delete-value: false # 逻辑未删除值(默认为 0)
  type-aliases-package: xyz.drinkice.nahidalibrary.model
  mapper-locations: classpath:mapper/*.xml
