version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: nahida
      POSTGRES_PASSWORD: nahida
      POSTGRES_DB: nahida_library
    ports:
      - "5431:5432"