version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nahida
      POSTGRES_PASSWORD: nahida
    ports:
      - "5432:5432"
    networks:
      - my-network