version: '3'
services:
  postgres:
    image: postgres:14
    container_name: nahida-pg
    restart: always
    environment:
      POSTGRES_USER: nahida
      POSTGRES_PASSWORD: nahida
      POSTGRES_DB: nahida_library
    volumes:
      - ./docker-volumes/.pg-data:/var/lib/postgres # 将数据目录挂载到本地目录以进行持久化
      - ./pg-init:/docker-entrypoint-initdb.d # 自动执行启动脚本
    ports:
      - "5431:5432"
    networks:
      - nahida-networks
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nahida-nacos
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
    ports:
      - "8847:8848"
    volumes:
      - ./docker-volumes/.nacos-data:/home/nacos/data
    networks:
      - nahida-networks

networks:
  nahida-networks: