version: '3'
services:
  n-gateway:
    image: lkzc19/n-gateway:latest
    container_name: n-gateway
    restart: always
    ports:
      - "9100:9100"
    networks:
      - nahida-networks

  n-account:
    image: lkzc19/n-svc-account:latest
    container_name: n-svc-account
    restart: always
    ports:
      - "9101:9101"
    networks:
      - nahida-networks
    depends_on: # 本服务依赖的服务，控制启动先后顺序
      - n-gateway

  n-core:
    image: lkzc19/n-svc-core:latest
    container_name: n-svc-core
    restart: always
    ports:
      - "9102:9102"
    networks:
      - nahida-networks
    depends_on:
      - n-gateway
      - n-account

networks:
  nahida-networks:
