spring:
  cloud:
    nacos:
      server-addr: nacos:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    gateway:
      routes:
        - id: account_route
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          ['/**']:
            allowedOrigins: "*"
            allowedMethods: "*"