server:
  port: 9000

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: account_route
          uri: http://localhost:9001
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1


