spring:
  cloud:
    nacos:
      server-addr: nacos:8848
      discovery:
        username: nacos
        password: nahida
        namespace: public
    gateway:
      routes:
        - id: account_route
          uri: lb://account-svc
          predicates:
            - Path=/api/account-svc/**
          filters:
            - StripPrefix=2
        - id: core_route
          uri: lb://core-svc
          predicates:
            - Path=/api/core-svc/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          ['/**']:
            allowedOrigins: "*"
            allowedMethods: "*"
