name: Docker Image

on:
  push:
    branches: [ "dev/luoshen19" ]

env:
  DOCKER_REPO_N_GATEWAY: lkzc19/n-gateway
  DOCKER_REPO_N_SVC_ACCOUNT: lkzc19/n-svc-account
  DOCKER_REPO_N_SVC_CORE: lkzc19/n-svc-core

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -DskipTests=true package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push n-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./n-gateway
          file: ./n-gateway/d.prod.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPO_N_GATEWAY }}:latest

      - name: Build and push n-svc-account
        uses: docker/build-push-action@v5
        with:
          context: ./n-svc-account
          file: ./n-svc-account/d.prod.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPO_N_SVC_ACCOUNT }}:latest

      - name: Build and push n-svc-core
        uses: docker/build-push-action@v5
        with:
          context: ./n-svc-core
          file: ./n-svc-core/d.prod.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPO_N_SVC_CORE }}:latest

      - name: Webhook
        run: |
          curl --location --request GET '${{ secrets.WEBHOOK_URL }}'
